### ISSUE TITLE
Text: Minimalist Data Wrangling with Python (page 75)

### ISSUE THREAD

**Issue by GeraldineDessa** [gagolews/datawranglingpy#1]
Small typo here... 3

<img width="447" alt="Screen Shot 2022-11-16 at 11 14 22 am" src="https://user-images.githubusercontent.com/83376990/202052066-430865cc-f6b1-4b0b-bbc2-917f3b543a74.png">

**Comment by gagolews** [comment]
Fixed, thank you!
