### ISSUE TITLE
Exercise 8.3 and others: normalisation

### ISSUE THREAD

**Issue by michaelgerloff** [gagolews/datawranglingpy#11]
I came across multiple instances where it was not clear what exaxctly was meant by normalisation.
For example Exercise 8.3 asks for standardisation (calculating the Z-score), normalisation(?) and min-max scaling (min-max normalization).  I assume that normalisation means calculating the mean normalisation. However, min-max scaling is a normalisation technique as well.
I'd recommend to spell out specifically what kind of normalisation needs to be calculated in excercises, to prevent confussion.

**Comment by gagolews** [comment]
Thanks for pointing this out. I'll add additional info that this refers to the operations discussed in Sec. 5.3.2. Application: Feature scaling.

Fix on the way.
