### ISSUE TITLE
Missing figures

### ISSUE THREAD

**Issue by michaelgerloff** [gagolews/datawranglingpy#12]
There are 4 missing 4 figures in chapter 9.
9.2, 9.4, 9.6, 9.8

**Comment by michaelgerloff** [comment]
Actually, I think those figures weren't planned as figures. There's code in the figure description that would translate in the following figures respectively.
![grafik](https://github.com/gagolews/datawranglingpy/assets/105306655/5023fa68-51aa-44a7-acd2-d5b73112c15d)

**Comment by gagolews** [comment]
Arrrgh, a recent update to knitr or docutils or sphinx must've break quite a few things. Thanks for reporting this, fix on the way!
