### ISSUE TITLE
missing word

### ISSUE THREAD

**Issue by Ed-ward-Harris** [gagolews/datawranglingpy#13]
In this section: https://datawranglingpy.gagolewski.com/chapter/000-preface.html#we-need-data-and-domain-knowledge

The sentence "Still, we need to familiar with the reality behind the numbers we have at hand, for example, by working closely with various experts in the field of our interest or pursuing study/research therein." Is missing a "be" at the start of the sentence

**Comment by gagolews** [comment]
Fixed; thanks.
