### ISSUE TITLE
Typo in 3.5.4. Modify in place or return a modified copy?

### ISSUE THREAD

**Issue by tomsing1** [gagolews/datawranglingpy#15]
I think there is a typo in section `3.5.4. Modify in place or return a modified copy?`:

The list.sort~~ed~~ method modifies the list it is applied on in place:

```
x = [5, 3, 2, 4, 1]
x.sort()  # modifies x in place and returns nothing
```

(e.g. `list.sort` instead of `list.sorted`)?

**Comment by gagolews** [comment]
You're right, thanks!
