### ISSUE TITLE
Dimensional mismatch in matrix equation

### ISSUE THREAD

**Issue by sedavbotero** [gagolews/datawranglingpy#18]
In [9.3.2](https://datawranglingpy.gagolewski.com/chapter/330-relationship.html#geometric-transformations-of-points) the equation
```math 
X = X'
\begin{bmatrix}
2 & 0 \\
0 & 0.5
\end{bmatrix}

\begin{bmatrix}
\cos{\frac{\pi}{6}} & \sin{\frac{\pi}{6}} \\
- \sin{\frac{\pi}{6}} & \cos{\frac{\pi}{6}} 
\end{bmatrix}
+
\begin{bmatrix}
3 & 2
\end{bmatrix}
 ```
there seems to be an error as the matrix $` X' `$ is (or at least seems to be) an $`n \times 2`$ matrix thus 
```math 
X'
\begin{bmatrix}
2 & 0 \\
0 & 0.5
\end{bmatrix}

\begin{bmatrix}
\cos{\frac{\pi}{6}} & \sin{\frac{\pi}{6}} \\
- \sin{\frac{\pi}{6}} & \cos{\frac{\pi}{6}} 
\end{bmatrix}
 ```
must also be an $` n \times 2 `$ matrix. This makes adding to it a $`1 \times2 `$ matrix nonsensical unless we take $` n = 1 `$. However, in the example code above in the book we take $` n = 10000`$ ⬇️ 

```python
np.random.seed(12345)
Xp = np.random.randn(10000, 2) * 0.25
```

**Comment by gagolews** [comment]
In Sec. 8.1.3.3, we've established the convention that:

![image](https://github.com/gagolews/datawranglingpy/assets/3193581/4db7c850-a982-47a4-bff0-1b77a95f04a0)

So the above formula represents the scaling, rotating, and shifting of X'.
