### ISSUE TITLE
misleading code comment

### ISSUE THREAD

**Issue by espinielli** [gagolews/datawranglingpy#3]
In [5.4.3 Slicing](https://datawranglingpy.gagolewski.com/chapter/220-transform-vector.html#slicing) the comment in part of the very first code snippet
```python
...
x[::-1]  # every second element
## array([50, 40, 30, 20, 10])
...
```
should say something like

```python
...
x[::-1]  # every element in reverse order
## array([50, 40, 30, 20, 10])
...
```

**Comment by gagolews** [comment]
Thanks, fix on the way!
