### ISSUE TITLE
backquoted operator names

### ISSUE THREAD

**Issue by espinielli** [gagolews/datawranglingpy#4]
In [5.4.3 Slicing](https://datawranglingpy.gagolewski.com/chapter/220-transform-vector.html#slicing)
it looks like the inline code `*=` has. ot been rendered correctly
```text
This did not modify the original vector, because we applied `*=` on a different object, which has not even been memorised after that operation took place.
```

**Comment by gagolews** [comment]
Ah, this is just the convention I use for the quoting of operator names - for consistency with my [R](https://deepr.gagolewski.com) book (R actually accepts any non-syntactically valid names if they are backticked). Might not make sense here, but it's just easier for me to use the same notation in two books, one thing to worry less about.

**Comment by espinielli** [comment]
Yeah, I though it was coming from RMarkdown...I am used to use the same but was expecting it to be converted to <code>+</code>...just brain compilation ;-)
