### ISSUE TITLE
missing subject

### ISSUE THREAD

**Issue by espinielli** [gagolews/datawranglingpy#5]
In [6.3.2. Pareto Distribution](https://datawranglingpy.gagolewski.com/chapter/230-distribution.html#pareto-distribution) I think the sentence

```text
This time, however, will be interested in not what is typical, but ...
```
is IMHO missing the subject.
I would write:

```text
This time, however, we will be interested in not what is typical, but ...
```

**Comment by gagolews** [comment]
Of course, thank you, fix on the way!
